NYU-Processor-Design/nyu-processor-design.github.io

src/design_notebooks/2023spring/un2021.md

Project Work:
* [Onboarding Lab 1](https://github.com/umanachi/vip_lab1): Completed Lab 1
This week, I explored the tools on our Anubis IDE and started understanding more about how to use git and GitHub. I completed lab 1 from the onboarding series and learned about toolchains and CMake, and how to implement them to run simple programs.
I struggled a bit with linking my directories and files created in Anubis to my GitHub repository, but with a bit of Googling and with help from the VIP website guides, I was able to push my directory to GitHub and link it above.
I will be unable to complete Lab 2 next week, but I will work on both Lab 2 and 3 during Week 3 (Feb 5-12).

Design Notebook Entry 1

---

src/design_notebooks/2023spring/spd7416.md

My Week 1 Notebook entry describing how I completed the first lab.

Week 1 Notebook entry

---

src/design_notebooks/2023spring/kcy4870.md

I have added my design notebook to the 2023spring folder with the first entry.

Design Notebook Entry 1 for Kevin

---

src/design_notebooks/2023spring/kc3977.md

Design Notebook kc3977

---

src/design_notebooks/2023spring/sc8781.md

Created my design notebook and added Week 1 progress.

---

src/getting_started/onboarding/03_verification.md

Fix for #15 
Signed-off-by: rishyak <hello@rishyak.com>

Fix spelling

---

src/design_notebooks/2023spring/rp3193.md
src/getting_started/notebooks/01_first_design.md

A little cheatsheet never hurt nobody.

Add markdown cheatsheet for reference.

---

src/design_notebooks/2023spring/spd7416.md

Sean's work on lab 2 for week 2.

Week 2 notebook entry

---

src/getting_started/onboarding/00_toc.md
src/getting_started/onboarding/01a_homebrew.md

Added the guide for installing homebrew and using it to install the needed dependencies. Also notified the 00_toc.md file to treat the new guide as 1a.

Added homebrew guide

---

src/design_notebooks/2023spring/spd7416.md

I fixed the spacing in my notebook md file and I updated my notebook to reflect that I fixed the ninja build system from my lab 1.

Sean fix md spacing

---

src/vip_course_docs/membership.md

Don't feel too bad, nobody can spell my name correctly on the first hundred tries.

Fixed typo in membership.md

---

src/getting_started/development/01_homebrew.md
src/getting_started/onboarding/02_cmake.md
src/getting_started/onboarding/04_verification.md
src/getting_started/onboarding/05_verification2.md

I fixed some spelling and grammar errors in the documentation along with some formatting errors in the Homebrew documentation.

Fixed Spelling Errors

---

src/getting_started/onboarding/05_verification2.md

Signed-off-by: rishyak <hello@rishyak.com>

chore: Lab 4 repo URL

---

src/getting_started/notebooks/03_dev_workflow.md
src/getting_started/notebooks/04_first_pr.md

- Git has changed, so the docs have been modernised too. 
- GitLens is pretty thoroughly integrated into VS Code now and the documentation mentions the "GitLens tab". Everything is now found in the "Source Control" tab. Updating this for anybody who sees this in the future with a clarification that most of these features are provided by GitLens.

docs(git): Modernise and update VSCode specifics

---

src/design_notebooks/2023spring/rp3193.md

docs(dn): update rishyak notebook 2023-02-05

---

src/design_notebooks/2023spring/spd7416.md

Sean Week 3 Notebook entry.

---

src/SUMMARY.md
src/design_notebooks/2023spring/kcy4870.md
src/getting_started/development/00_toc.md
src/getting_started/development/03_wsl_vscode.md

This pull request contains updates to my project documentation for the week of 2/10/2023 and the first version of the Windows WSL documentation.

docs(dn) Project notebook and WSL documentation

---

src/design_notebooks/2023spring/nvg7278.md

Hello World

---

src/design_notebooks/2023spring/kcy4870.md

Added design notebook entry for the week of 2/17.

doc(dn): Kevin entry 2023-02-17

---

src/getting_started/notebooks/00_toc.md
src/getting_started/notebooks/04_first_pr.md
src/getting_started/notebooks/05_collab.md

Draft of guide for working collaboratively (pull requests, issues/questions, additional support)

docs(guides): create docs for teamwork

---

src/design_notebooks/2023spring/kcy4870.md

Design notebook entry for 2-24-2023 attempt 2. I had forgotten how to properly sync my branches but @rishyak gave me some advice on #73 so I redid it correctly (I hope) this time.

docs(dn): Kevin's design notebook for 2-24-2023

---

src/design_notebooks/2023spring/un2021.md

apologies for the late entry - wanted to finish some guide editing before I wrote the dn

docs(dn): Uma entry 2023-02-26

---

src/design_notebooks/2023spring/spd7416.md

My design notebook entry for the week of 3_27

3 27 entry

---

src/design_notebooks/2023spring/rp3193.md

Properly forgot design notebooks were a thing.
I will continue my work on the manger next week because of a midterm staring right at me. 
Calling all CE/EE people, I'll need to talk through my manager design at some point.

docs(dn): rishyak entries 2023-04-02 & 2023-04-09

---

src/design_notebooks/2023fall/xd2305.md

xd2305-Lab1

---

src/getting_started/onboarding/07_dependencies.md
src/getting_started/onboarding/08_cpu.md
src/getting_started/onboarding/08_paths.md

Ready to merge once Documentation Team portion of Lab 7 is finished

docs(lab7): change to "becoming a processor designer"

---

src/design_notebooks/2023fall/aay268.md

docs(dn): Auryn 10.7.23

---

src/design_notebooks/2023fall/xd2305.md

docs: Xingzhi Dai report week  10/5

docs: Xingzhi Dai report week 10/5

---

src/design_notebooks/2023fall/dk4461.md

modified:   src/design_notebooks/2023fall/dk4461.md

chore: Updating Design Notebook Entries for Semester

---

src/design_notebooks/2023fall/rp3193.md

Thank you to Auryn for the reminder.

docs(dn): rishyak entries fall 2023

---

src/design_notebooks/2023fall/aay268.md

I finished all of the design notebooks~! Yay :D

docs(dn): Auryn 12.12.23 - Final Design Notebook

---

src/design_notebooks/2023fall/tnv2002.md

I tried using Conventional Commits syntax this time! I'm wondering what the type should be for this commit, I put `docs` but I'm not sure...

docs(dn): thu final-doc 2023-12-14

---

src/SUMMARY.md
src/design_notebooks/2024spring/00_toc.md
src/design_notebooks/2024spring/xd2305.md

docs(dn): week 6/2/2024

---

src/SUMMARY.md
src/design_notebooks/2024spring/00_toc.md
src/design_notebooks/2024spring/aj4128.md
src/vip_course_docs/membership.md

Created Design notebook for Aditya Deepak Joshi, as part of VIP Project for Spring 2024

Pull request for AJ4128

---

src/design_notebooks/2024spring/cb5179.md

Was behind on commits but now I am caught up.

Opened a new pull request to add the rest of my design notebook entires.

---

src/design_notebooks/2024spring/hg2622.md

docx(dn): kevin(hg2622) notebook

---

src/design_notebooks/2024spring/kc3977.md

A completed design notebook for the Spring 2024 semester.

docs(dn):  completed kc3977 design notebook for Spring 2024

---

src/design_notebooks/2024spring/gj2148.md

Given that the branch was unmerged from last week. I decided to add this week's design notebook updates to the same branch used for last week's update.

docs(dn): James 2024-02-18

---

src/SUMMARY.md
src/design_notebooks/2024fall/00_toc.md
src/design_notebooks/2024fall/dvl2013.md

Dmitri Lyalikov create initial design notebook for fall 2024. 

---

src/SUMMARY.md
src/design_notebooks/2024fall/00_toc.md
src/design_notebooks/2024fall/dk4461.md

docs(dc):Fall 2024 Design Notebook Creation

---

src/SUMMARY.md
src/design_notebooks/2024fall/00_toc.md
src/design_notebooks/2024fall/cb5179.md

First commit. Created the design notebook and  backdated for last week.

Create Cameron's Design Notebook - cb5179.md

---

src/design_notebooks/2024fall/nm4207.md

docs(dn):noahmayssmith dn 9/27/24

---

src/design_notebooks/2024fall/cb5179.md

Added my entries from the past few weeks.

docs(dn): update \<cb5179\> dn for week of october 18th

---

src/design_notebooks/2024fall/dvl2013.md

Added local changes to design notebook and attachment of onboarding lab forks for final submisison. Have a good break everyone.

docs(dn): Dmitri dn 12/16 

---

src/design_notebooks/2025spring/gj2148.md

Roughly first half of this semester's design notebooks. Will upload the remainder of work soon

docs(dn): James Jin S25 bulk upload part 1
